### ISSUE TITLE
Something is wrong here

### ISSUE THREAD

**Issue by jethanSarita** [JoshCunningHum/SchEdu#5]
Teacher distribution and section distribution is not working for
Account: JethanTest
Timetable: Actual School Schedule Test

(If my account is accessible please check) I made sure the parameters are exact (I haven't tried the customization, will do after this.) I think there's something wrong with the Algo or it's just my parameters input.

Only one teacher is distributed to a class and only one room is distributed classes

I am unsure if it's account problem or not

I just checked the customization feature in "1 - Move classes in rooms" class selection cant be selected and can only edit the generated classes.

I may need demonstration

**Comment by JoshCunningHum** [comment]
we can do a demo for the customization, just chat me and yes, only the generated version can be edited. Because of reasons:

1. Once you generate and you edit the parameters, the generated version is already outdated, therefore it will be inconsistent if we provide the latest parameters to the outdated data. An already deleted instructor could still be existing in the timetable hence the inconsistency
2. The customization or customize is designed to be the editor, not the creator. The point of it is to customize the generated timetable as our app is for generating it with the algorithm, the customization being for the special and rare cases.

Thus, only the generated data can be edited.

>  "1 - Move classes in rooms" class selection cant be selected
I don't quite understand what this means
